web-application/src/carts/urls.py
from django.urls import path, include


from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view
)

urlpatterns = [
    path(r'^$', cart_home, name='home'),
    path(r'^checkout/$', checkout_home, name='checkout'),
    path(r'^update/$', cart_update, name='update'),
    path(r'^checkout/success$', checkout_done_view, name='success'),

]

web-application/src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView


from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page

urlpatterns = [
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('', home_page, name='home'),
    path('login/', login_page, name='login'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cart/', include(("carts.urls","carts"), namespace='cart')),
    path('register/', register_page, name='register'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('products/', include(("products.urls","products"), namespace='products')),
    path('search/', include(("search.urls","search"), namespace='search')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-application/src/carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product


User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user        = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)




def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)




def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08) # 8% tax
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

web-application/src/carts/views.py
from django.shortcuts import render, redirect


from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail

from addresses.forms import AddressForm
from addresses.models import Address

from billing.models import BillingProfile
from orders.models import Order
from products.models import Product
from .models import Cart

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user, product is gone?")
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_items'] = cart_obj.products.count()
    return redirect("cart:home")



def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")  
    
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id) 
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        "check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs,
    }
    return render(request, "carts/checkout.html", context)


def checkout_done_view(request):
    return render(request, "carts/checkout-done.html", {})

web-application/src/carts/templates/carts/checkout-done.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<style type="text/css">

body {
	background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
	background-size: 400% 400%;
	animation: gradient 8s ease infinite;
}

@keyframes gradient {
	0% {
		background-position: 0% 50%;
	}
	50% {
		background-position: 100% 50%;
	}
	100% {
		background-position: 0% 50%;
	}
}

.za
{
  -webkit-animation: colorchange 5s ease infinite ;
}

@-webkit-keyframes colorchange {
      0% {
        
        color: red;
      }
      
      10% {
        
        color: gold;
      }
      
      20% {
        
        color: lightblue;
      }
      
      30% {
        
        color: black;
      }
      
      40% {
        
        color: lightgreen;
      }
      
      50% {
        
        color: black;
      }
      
      60% {
        
        color: purple;
      }
      
      70% {
        
        color: teal;
      }
      80% {
     
        color: black;
      }
      
      90% {
     
        color: white;
      }
      
      100% {
        
        color: orange;
      }
    }


.zc
{
	margin-top:2%;
	font-size:75px;
	margin-left: 45%;
	margin-bottom: 5%;
	color:white;
	 text-shadow: 2px 2px 0px rgba(255,0,255,0.3), 8px 12px 3px rgba(0,100,0,0.7);
}

.zfo
  {
    font-size:50px;
    color:white;
    
    margin-top: 8%;
    margin-left:18%;
    letter-spacing: 70px;
    -webkit-text-stroke: 0.8px black;
    
    text-align: center;
  }

  .zfo:hover
  {
    
    
    -webkit-text-stroke: 2px black;
    transform:scale(1.4);
    transition-duration: 0.7s;
  }

  h5
  {
  text-align: justify;
  font: 100 85px/1.5 'Pacifico', Helvetica, sans-serif;
  color: white;
  text-shadow: 2px 2px 0px rgba(255,0,255,0.3), 8px 12px 3px rgba(0,100,0,0.7);
  -webkit-text-stroke: 1px gold;
  }


  h6
  {
  
  margin-top:7.5%;
  font: 400 100px/2 'Arizonia', Helvetica, sans-serif;
  font-size:55px;
  text-align: center;
  text-shadow: 2px 2px 0px rgba(255,0,255,0.3), 4px 4px 3px rgba(0,100,0,0.7);
  letter-spacing: 3px;
  -webkit-text-stroke: 0.5px red;

  }

  #myVideo {
  position: fixed;
  right: 0;
  bottom: 0;
  min-width: 100%;
  min-height: 100%;
  opacity: 0.1;
}



</style>

<video autoplay muted loop id="myVideo">
  <source src="{% static 'img/Tulum.mp4' %}" type="video/mp4">
</video>


<i class="fa fa-superpowers zc"></i>
<!--<div class="col-6 mx-auto py-5 text-center">
    <h4 class="display-2">
        Thank you for your order!
    </h4>
</div>-->

<h5 class="za"> Thank You For Your Orders!</h5>
<h6>Email us At: zyx@gmail.com</h6>
<a href="#"><i class="fa fa-twitter zfo"></i></a>
<a href="#"><i class="fa fa-facebook-official zfo"></i></a>
<a href="#"><i class="fa fa-pinterest zfo" aria-hidden="true"></i></a>
<video autoplay muted loop id="myVideo">
  <source src="{% static 'img/Tulum.mp4' %}" type="video/mp4">
</video>
{% endblock %}

web-application/src/carts/templates/carts/checkout.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<style type="text/css">



body{
    background-image: url("{% static 'img/shirtim.jpg' %} ");
    background-size:cover;
    background-attachment:fixed;
    /*background: linear-gradient(-120deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
  animation: gradient 7s ease infinite;
  background-size: 400% 400%;*/

  }

  .xcv
  {
    background: url("{% static 'img/shirtim.jpg' %} ");
    background-size:75%;
    background-attachment:fixed;
    background-repeat: no-repeat;
    background-position: center;
    border-radius: 2px;
    margin-top: 2.5%;
    box-shadow: -1px 1px 50px 10px grey;



  }

  .dvd div
  {
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.6);
  }


  .form-control
  {
    background: transparent;
    border-radius:0px;
    border:0px;
    border-bottom: 1px solid lightgreen;
    font-size:21px;
    margin-top: 35px;
    padding-bottom: -20px;

    padding: 0px;
    color:white;
    line-height: 2;


  }


  h6{
  color:lightgreen;
  text-align: center;
 
  font-size: 450%;
  margin-left: 0%;
  /*left: 60%;
  top: 67%;*/
  margin-top: 0px;
  /*transform: translate(-75%,-190%);*/
  letter-spacing: 2.5px;
  font-weight: 75;
  text-shadow: 1px 1px 1px rgba(0,0,0,0.3), 4px 4px 1px rgba(0,0,0,0.7);

  background: linear-gradient(100deg, #1f0752, #8f0070, #30a6d5, #ffd00f);
  background-size: 400% 400%;
  animation: gradient 8s ease-out infinite;
  
}

  




/*.col-md-6 
  {
    
    border-radius: 0px 100px 0px 100px;
    padding-top:20px;
    margin-top: 0px;
    margin-bottom: 0px;
    left:25%;


    height: 710px;
    background: rgba(0,0,0,0.9);
  }*/
.psc
{
  margin-left: 25%;


}

  /*.col-md-12 guest login page
    {
    box-shadow: -1px 1px 50px 10px grey;
    border-radius: 1000px 1000px 1000px 1000px;
    padding-top:20px;
    margin-top: 10px;
    margin-bottom: 50px;



    height: 280px;
    background: rgba(0,0,0,0.73);
  }
  */

  h5{

    
    color:white;
    position:absolute;
    font-size: 300%;
   
  
  
  
  letter-spacing: 2px;
  font-weight: 100;
  }



 h4{
    color:lightgreen;
    position:relative;
    font-size: 300%;
   
  
  
  
  letter-spacing: 2px;
  font-weight: 100;


  display: block;
  
  margin-top: 0px;
  margin-bottom: 0px;
  margin-bottom: 5px;
  margin-left: 2%;
  margin-right: 0;
  

  }


.btn-success
 {
    margin-top: 5px;
    margin-bottom: 0px;
    font-size: 25px;
    margin-left:40%;
    width:200px;
    font: 100 30px/1.5 'Pacifico', Helvetica, sans-serif;
  color: lightblue;
  padding: 3px -10px 3px -10px;
  text-shadow: 1px 1px 1px rgba(255,0,255,0.3), 2px 2px 1px rgba(0,100,0,0.7);
  text-align: center;
  border-radius: 30px;
  
    
  }

.btn-default
{
  margin-top: 5px;
    margin-bottom: 30px;
    font-size: 25px;
    
    width:200px;
   
  padding: 3px -10px 3px -10px;
  
  text-align: center;
  border-radius: 30px;
}

p
{
  font: 200 35px/1.6 'Allan', Helvetica, sans-serif;
  color: gold;
  text-shadow: 1px 1px 1px rgba(0,0,0,0.1), 3px 3px 1px rgba(0,0,0,0.5);
  letter-spacing: 3px;
  margin-top: 35px;
  margin-bottom: 30px;
  margin-left: 0%;
  background: linear-gradient(60deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
  animation: gradient 1s ease infinite;

  text-align: center;
}

@keyframes gradient {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }

  
#myVideo {
  position: fixed;
  right: 0;
  bottom: 0;
  min-width: 100%;
  min-height: 100%;
  opacity: 0.1;




</style>





{% if not billing_profile %}
    <div class='row text-center xcv dvd'>
      <div>
    <!--<div class='col-12 col-md-12'>
        <h5 align="center">GUEST EMAIL</h5>
        

        {% url "guest_register" as guest_register_url %}
        {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
    </div> -->
    <div class='col-12 col-md-6 col-sm-12 psc'>
        <h5 class ="nb" align="center">SIGN-IN</h5>
        
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}

        <h4 align="center">OR</h4>
        <br>
        <p>
        </p>

        <h5 align="center">GUEST EMAIL</h5>
        

        {% url "guest_register" as guest_register_url %}
        {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
    </div>
  </div>
    

    </div>

{% else %}

        {% if not object.shipping_address %}

        


         <div class='row'>
            <div class='col-12'>
                <p class='lead'>Shipping Address</p>
                <hr/>
            </div>
            <div class='col-6'>




                    {% url "checkout_address_create" as checkout_address_create %}
                    {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}'



             </div>
         <div class='col-6'>
            {% url 'checkout_address_reuse' as checkout_address_reuse %}
            {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
            </div>
        </div>


        {% elif not object.billing_address %}
        <div class='row'>
            <div class='col-12'>
                 <p class='lead'>Billing Address</p>
                <hr/>
            </div>
            <div class='col-6'>

            {% url "checkout_address_create" as checkout_address_create %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
            </div>
              <div class='col-6'>
                {% url 'checkout_address_reuse' as checkout_address_reuse %}
             {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri  address_type='billing' action_url=checkout_address_reuse %}
         </div>


        </div>
        {% else %}

            <h6>FINALIZE CHECKOUT</h6>
            <p><u>Cart items</u> : {% for product in object.cart.products.all %}
                {{ product }}
                {% if not forloop.last%},
                {% endif %}
                {% endfor %}

            </p>
            <p><u>Shipping Address</u> : {{ object.shipping_address.get_address}}</p>
            <p><u>Billling Address</u> : {{ object.billing_address.get_address}}</p>
            <p><u>Cart Total</u> : $ {{ object.cart.total }}</p>
            <p><u>Shipping Total</u> : $ {{ object.shipping_total }}</p>
            <p><u>Order Total</u> : $ {{ object.total }}</p>
            <form class='form' method='POST' action="">{% csrf_token %}
                <button class="btn btn-success" type='submit'>Checkout</button>
            </form>
        {% endif %}
{% endif %}



{% endblock %}

web-application/src/carts/templates/carts/home.html
{% extends "base.html" %}


{% block content %}
{% load static %}



<style type="text/css">

  body {
  background: linear-gradient(100deg, #1f0752, #8f0070, #30a6d5, #ffd00f);
  background-size: 400% 400%;
  animation: gradient 8s ease-out infinite;
}

@keyframes gradient {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}

.fes
{

  font-family: 'Allan';
  font-size:40px;
  letter-spacing:3px;
  color:lightblue;
  -webkit-text-stroke: 0.1px white;

}
a
{
  color:lightblue;
}

.des
{
  font: 100 30px/1.5 'Pacifico', Helvetica, sans-serif;
  color: lightgreen;
  -webkit-text-stroke: 0.3px black;
}
h6
{
   color:yellow;
  
 font: 100 30px/1.5 'Pacifico', Helvetica, sans-serif;
  font-size: 450%;
  
  /*left: 60%;
  top: 67%;*/
  margin-bottom: 5%;
  /*transform: translate(-75%,-190%);*/
  letter-spacing: 10px;
  font-weight: 75;
  text-shadow: 1px 1px 1px rgba(0,0,0,0.3), 8px 8px 1px rgba(0,0,0,0.7);
  -webkit-text-stroke: 1px white;
}


.btn-success
{
  margin-top:5%;
  font-family: Allan;
  letter-spacing: 2px;
  border-radius: 20px;
  font-size: 20px;
  -webkit-text-stroke: 0.5px white;

}

.vb
{
  font: 100 50px/1.1  Comic sans-serif;
  color: white;
  background-color: black;
  padding-left:3%;
  text-align:center;
  letter-spacing: 7px;
  margin-left: 5%;
  margin-top: 20%;
   -webkit-text-stroke: 0.3px black;
}


#myVideo {
  position: fixed;
  right: 0;
  bottom: 0;
  min-width: 100%;
  min-height: 100%;
  opacity: 0.4;
}

.table
{
  background-color: black;
  opacity:0.7;
}
</style>




<video autoplay muted loop id="myVideo">
  <source src="{% static 'img/apple.mp4' %}" type="video/mp4">
</video>



<h6><u>Your Cart</u></h6>

{% if cart.products.exists %}
<table class="table">
  <thead>
    <tr>
      <th class="fes">#</th>
      <th class="fes">Product Name</th>
      <th class="fes">Product Price</th>
    </tr>
  </thead>
  <tbody class="des">
    {% for product in cart.products.all %}
    <tr>
      <th scope="row">{{ forloop.counter }}.</th>
      <td>
        <a href='{{ product.get_absolute_url }}'>{{ product.title }}</a> 


        {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
      </td>
      <td>$ {{ product.price }}</td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan="2"></td>
      <td><b>Subtotal:</b> $ {{ cart.subtotal }}</td>
    </tr>
    <tr>
      <td colspan="2"></td>
      <td><b>Total:</b> $ {{ cart.total }}</td>
    </tr>
    <tr>
      <td colspan="2"></td>
      <td><a class='btn btn-success' href='{% url "cart:checkout" %}'>Checkout</a></td>
    </tr>

  </tbody>
</table>

{% else %}
<p class='lead vb'> Sorry! Cart   is   empty</p>
{% endif %}


{% endblock %}