web-application/src/carts/urls.py
from django.urls import path, include


from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view
)

urlpatterns = [
    path(r'^$', cart_home, name='home'),
    path(r'^checkout/$', checkout_home, name='checkout'),
    path(r'^update/$', cart_update, name='update'),
    path(r'^checkout/success$', checkout_done_view, name='success'),

]

web-application/src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView


from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page

urlpatterns = [
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('', home_page, name='home'),
    path('login/', login_page, name='login'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cart/', include(("carts.urls","carts"), namespace='cart')),
    path('register/', register_page, name='register'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('products/', include(("products.urls","products"), namespace='products')),
    path('search/', include(("search.urls","search"), namespace='search')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-application/src/products/urls.py
from django.urls import path, include


from .views import (
        ProductListView, 
        ProductDetailSlugView, 
        )

urlpatterns = [
    path(r'^$', ProductListView.as_view(), name='list'),
    path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

web-application/src/products/models.py
import random
import os
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

from ecommerce.utils import unique_slug_generator

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    # print(instance)
    #print(filename)
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(
            new_filename=new_filename, 
            final_filename=final_filename
            )

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
        lookups = (Q(title__icontains=query) | 
                  Q(description__icontains=query) |
                  Q(price__icontains=query) |
                  Q(tag__title__icontains=query)
                  )
        # tshirt, t-shirt, t shirt, red, green, blue,
        return self.filter(lookups).distinct()

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self): #Product.objects.featured() 
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id) # Product.objects == self.get_queryset()
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)


class Product(models.Model):
    title           = models.CharField(max_length=120)
    slug            = models.SlugField(blank=True, unique=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    image           = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured        = models.BooleanField(default=False)
    active          = models.BooleanField(default=True)
    #timestamp       = models.DateTimeField(auto_now_add=True)

    objects = ProductManager()

    def get_absolute_url(self):
        #return "/products/{slug}/".format(slug=self.slug)
        return reverse("products:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    @property
    def name(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

web-application/src/products/views.py
# from django.views import ListView
from django.http import Http404
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404

from carts.models import Cart

from .models import Product


class ProductFeaturedListView(ListView):
    template_name = "products/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()


class ProductFeaturedDetailView(DetailView):
    queryset = Product.objects.all().featured()
    template_name = "products/featured-detail.html"

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     return Product.objects.featured()



class ProductListView(ListView):
    template_name = "products/list.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     print(context)
    #     return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()


def product_list_view(request):
    queryset = Product.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "products/list.html", context)



class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        #instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("Uhhmmm ")
        return instance



class ProductDetailView(DetailView):
    #queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        # context['abc'] = 123
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Product.objects.get_by_id(pk)
        if instance is None:
            raise Http404("Product doesn't exist")
        return instance

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #     return Product.objects.filter(pk=pk)


def product_detail_view(request, pk=None, *args, **kwargs):
    # instance = Product.objects.get(pk=pk, featured=True) #id
    # instance = get_object_or_404(Product, pk=pk, featured=True)
    # try:
    #     instance = Product.objects.get(id=pk)
    # except Product.DoesNotExist:
    #     print('no product here')
    #     raise Http404("Product doesn't exist")
    # except:
    #     print("huh?")

    instance = Product.objects.get_by_id(pk)
    if instance is None:
        raise Http404("Product doesn't exist")
    #print(instance)
    # qs  = Product.objects.filter(id=pk)

    # #print(qs)
    # if qs.exists() and qs.count() == 1: # len(qs)
    #     instance = qs.first()
    # else:
    #     raise Http404("Product doesn't exist")

    context = {
        'object': instance
    }
    return render(request, "products/detail.html", context)

web-application/src/products/templates/products/detail.html
{% extends "base.html" %}

{% load static %}
{% block content %}
{% url 'cart:home' as cart_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}

<style type="text/css">
    
body{
    background-color: black;

}
    h4{
        color:black;
  
  font-size: 350%;
  margin-top: 10px;
  
  letter-spacing: 2px;
  font-weight: 100;
  text-shadow: 0px 4px 6px rgba(65,125,90,0.9);

    }
    h5{
         font: 100 35px/1.5 'Pacifico', Helvetica, sans-serif;
         color:green;
         margin-bottom: 10px;
    }

    .col-4
    {
        margin-left: -12%;
        margin-top: 3%;
    }


    .col-6
    {
        margin-top: 3.3%;
        margin-left:10%;
        background-image: url("{% static 'img/bgrnd1.jpg' %} ") ;
        padding: 20px 0px 35px 50px;

    }

    .cv
    {
        width:350px;
        height:450px;
        margin-top: 15%;
        /*box-shadow: 0px 2px 6px 3px rgba(0,0,0,0.4);*/
        box-shadow: 0 6px 10px 6px rgba(255,255,255,0.4);
        
    }
    .xc{
        font-size: 40px;
        color:#455A64;
        margin-bottom: 30px;
    }
    h6
    {
        font-size: 50px;
        color: #18FFFF;
        text-align: justify-all;
        font-weight: 300;
        margin-left: 25px;


    }
    .vb
    {
        font-size: 25px;
        align-content: center;
        margin-top: 4%;
    }
    textarea
    {
        font-family: Pacifico;
        resize:none;
    }
    .col-2
    {
        margin-top: 3.7%;
        margin-left: 11%;
        margin-right:-15%;
        /*background-color: grey;*/
        padding-left:27px;
        padding-top: 5px;

       /* opacity:0.6;*/
       
        

       
    }

    .bm
    {
        font-size: 80px;
        color:white;
        margin-bottom: 5%;
        margin-left:10px;
        
    }
    
    #myVideo {
  position: fixed;
  right: 0;
  bottom: 0;
  min-width: 100%;
  min-height: 100%;
  opacity: 0.6;
}

    
</style>
<video autoplay muted loop id="myVideo">
  <source src="{% static 'img/clothing.mp4' %}" type="video/mp4">
</video>


    <div class='row'>
        <div class='col-4'>

                {% if object.image %}
                <!--<div class="mb-3" style="min-width: 640px;" style="min-height:600px;">-->        
                <img src='{{ object.image.url }}' class="cv" alt="image">
            </div>
                        
                            
                        <div class="col-6">
                            
                                <h4 class="">{{ object.title }}</h4>
                                <h5 class="">Price: $ {{ object.price }}</h5>
                                <i class="fa fa-truck xc"></i> <b>Fast Delivery</b>
                                <i class="fa fa-check-circle xc"></i> <b>Verified Product</b><br>

                                <textarea readonly id="w3mission" rows="8" cols="50">{{ object.description }}</textarea>

                {% endif %}
        
        <div class="btn btn-outline-dark vb">
            {% include 'products/snippets/update-cart.html' with product=object cart=cart %}

        </div>
</div>
<div class="col-2">
    
<a class="bm" href="{{ cart_url }}"> <i class="fa fa-shopping-cart bm"></i></a>
<h6> OR</h6>

<a href="{{ contact_url }}" class="btn btn-warning btn-lg {% if request.path == contact_url %}active{% endif %} my-5" ><b>FEEDBACK</b></a>

<h6> OR </h6>
<a href="{{ product_list_url }}" class="btn btn-danger btn-lg animated tada {% if request.path == product_list_url %}active{% endif %} my-5"><b>PRODUCTS</b></a>
      

</div>
</div>
</div>




<!--{% endblock %}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src='{{ object.image.url }}' class="card-img" alt="image">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ instance.title }}</h5>
        <p class="card-text">{{ object.price }}</p>
        
      </div>
    </div>
  </div>
</div>
-->

web-application/src/products/templates/products/featured-detail.html
{{ object.title }} <br/>
{{ object.description }} <br/>
{% if object.image %}
    <img src='{{ object.image.url }}' class='img-fluid' width="80" height="150">
{% endif %}

web-application/src/products/templates/products/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<style type="text/css">


	.col-6
	{
		margin-left: -5%;

	}

	.col-6
	{

	}
	p
	{
		

	}

	.bd
	{

	}
 
   /*#myVideo {
  
  right: 0;
  bottom: 0;
  
  opacity: 0.6;
}
.vid
{
	height:700px;
  width:100%;
  display:flex;
  justify-content: center;
  align-items:center;
  background-repeat: no-repeat;
  background-size: cover;
  margin-left: 0px;
  margin-top: -1%;
  margin-bottom: 0px;
}*/

/*.container{
  width: 152%;
  height: 100vh;
  position:relative;
  margin-left:-26%;
  
  
  /*background: linear-gradient(100deg, #1f0752, #8f0070, #30a6d5, #ffd00f);
  background-size: 200% 200%;
  animation: gradient 8s ease-out infinite;
  z-index: 10

}
  */
 

 /*.container video{
  object-fit: cover;
  width: 100%;
  height: 70%;
  position: relative;
  margin-top: -8%;
  z-index:0;
  

   
}

@keyframes gradient {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
*/


.row-4{
  background-image: url("{% static 'img/ph3.jpg' %} ") ;
  /*background: linear-gradient(to bottom, rgba(0,0,0,0.78) 12%, rgba(16,58,80,0.2) 100%);*/
  height:725px;
  width:139%;
  display:flex;
  justify-content: center;
  align-items:center;
  background-repeat: no-repeat;
  background-size: cover;
  margin-left: -13%;
  margin-top: -3%;
  margin-bottom: 0px;

  /*animation-name: SideRight;
  animation-duration: 3s;*/

 
  }
.bsc 
  {

  
  background-color: rgba(0, 0, 0, 0.3);
}






.sidenav {
  height: 100%; /* Full-height: remove this if you want "auto" height */
  width: 150px; /* Set the width of the sidebar */
  position: fixed; /* Fixed Sidebar (stay in place on scroll) */
  z-index: 1; /* Stay on top */
  top: 0; /* Stay at the top */
  left: 0;
  background-color: #795548; /* Black */
  overflow-x: hidden; /* Disable horizontal scroll */
  padding-top: 20px;
  margin-top:3%;
  border:5px;
}


.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #C6FF00;
  display: block;
}

.sidenav a:hover
{
	color:#00E676;
}

.zeta
{
	width:141%;
	margin-left:-15%;
	color:teal;

}

.display-4
  {
    color:#1A237E;
    margin-left: 1%;
    margin-top: 0px;
    margin-bottom: 40px;
    text-shadow: 3px 4px 12px rgba(0,0,0,0.6);
    -webkit-text-stroke: 1px 1A237E;
    font-family:"pacifico";
  }
.icn
{
	width:150;
	height:120px;
	margin: 15px 20px 15px 20px  ;
}
.icnsam
{
	width:165px;
	height:135px;
}
.icnall

{
	width:195px;
	height:165px;
}

.icnmi
{
	margin-left:75px;
	width:145px;
	height:125px;
}
.icnone
{
  width:90px;
  height:90px;
  margin-left:75px;
  margin-right:80px;
}


.myVideo
{
	margin-left:-13%;
	width:95%;
	margin-top:10%;
	margin-bottom: 10%;
	opacity: 0.6;
  border: 10px solid black;
box-sizing: border-box;
  

}

.bounceInLeft
{
	transition: all 1.3s ease;
}
.col-10
{
  
}

.col-2
{
  margin-top: 6%;
  
  
  
}

.pv
{
  
  font-size:20px;
  margin-left:-80%;
  color:grey;
  margin-bottom:20%;
  margin-top:40%;
}

.pv1
{
   font-size:20px;
  margin-right:-400%;
  color:grey
  margin-top:10%;
  margin-bottom:20%;

}
.pv2
{
   font-size:20px;
  color:#283593;
  color:grey
  margin-top:80%;
  margin-left:-160%;
}





</style>


<div class="sidenav">
  <a href="#">Books</a>
  <a href="#">Clothing</a>
  <a href="#">Jewellery</a>
  <a href="#">Beauty</a>
  <a href="#">Health</a>
  <a href="#">Electronics</a>
  <a href="#">Essentials</a>
  <a href="#">Innovation</a>
</div>

<div class="main">


<!--<div class="Container">
	 <video autoplay loop muted class="video">
      <source src="{% static 'img/apple.mp4' %}">
   </video>
	<div class="content">
  <h1>Heading</h1>
  <p>Lorem ipsum...</p>
  
</div>

  
</div>-->
  




<div class='row-4 animated bounceInLeft bsc'>
</div>

  
    
      
        

        
          <!--<a href="{{ product_list_url }}" class="btn btn-danger btn-lg animated tada {% if request.path == product_list_url %}active{% endif %} my-5"><b>SHOP-NOW</b></a>
      
        </p>
    
  </h6>
      <img src="{% static 'img/sh-mall.jpeg' %} " 
    
</div>
</div>-->

<div class="jumbotron jumbotron-fluid my-0 py-2 zeta" style="background-color:white">
  <div class="container-fluid" align="center">
  	 <h3 class="display-4 py-4" align="center"><u>Brands</u></h3><p>
    </p>
    <div class="container">
    <img class="icn" src="{% static 'img/adidas.png' %}" height="200" alt="...">
    <img class="icn" src="{% static 'img/nike.png' %}" height="200" alt="...">

<img class="icn" src="{% static 'img/puma.png' %}" height="200" alt="...">

<img class="icn icnsam" src="{% static 'img/sam.png' %}" height="200" alt="...">

<img class="icnall" src="{% static 'img/allen.png' %}" height="200" alt="...">

<img class="icn icnlevi" src="{% static 'img/levi.png' %}" height="200" alt="...">

<img class="icn icnmi" src="{% static 'img/mi.png' %}" height="200" alt="...">
<img class="icn icnone" src="{% static 'img/one.jfif' %}" height="200" alt="...">
<img class="icn" src="{% static 'img/sony1.png' %}" height="200" alt="...">



  
</div>
</div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-10 no-gutters">
	<video autoplay muted loop class="myVideo">
  <source src="{% static 'img/apple.mp4' %}" type="video/mp4">
</video>
</div>
<div class="col-2 no-gutters">
  <p class="pv0"> <h5><u>Testimonials</u></h5><br></p>

  <p class="pv"> "I am very happy, with the product and service provided by ecomme"<br>
  --Azerio Auditore</p>
  <div class="row">
    <div class="col-6"> 
      <p class="pv1">"It is a awesome website, very user-friendly and smooth"<br>
  --John Herbes</p>
    </div>
    <div class="col-8">
      <p class="pv2">"Its like a gift to find this site, very cheap and good quality products"<br>
  --Jordan Piazo</p>
    </div>

</div>
</div>
</div>

<div class='row'>
	

    {% for obj in object_list %}
        <div class='col-3 py-4' >
            <div style='min-height: 125px;'>
        
        {% include 'products/snippets/card.html' with instance=obj %}  
        </div>
        
         </div>
        

     
     
      
       
    
    {% endfor %}

</div>




</div>



{% endblock %}