web-application/src/carts/urls.py
from django.urls import path, include


from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view
)

urlpatterns = [
    path(r'^$', cart_home, name='home'),
    path(r'^checkout/$', checkout_home, name='checkout'),
    path(r'^update/$', cart_update, name='update'),
    path(r'^checkout/success$', checkout_done_view, name='success'),

]

web-application/src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView


from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page

urlpatterns = [
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('', home_page, name='home'),
    path('login/', login_page, name='login'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cart/', include(("carts.urls","carts"), namespace='cart')),
    path('register/', register_page, name='register'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('products/', include(("products.urls","products"), namespace='products')),
    path('search/', include(("search.urls","search"), namespace='search')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-application/src/products/urls.py
from django.urls import path, include


from .views import (
        ProductListView, 
        ProductDetailSlugView, 
        )

urlpatterns = [
    path(r'^$', ProductListView.as_view(), name='list'),
    path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

web-application/src/products/models.py
import random
import os
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

from ecommerce.utils import unique_slug_generator

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    # print(instance)
    #print(filename)
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(
            new_filename=new_filename, 
            final_filename=final_filename
            )

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
        lookups = (Q(title__icontains=query) | 
                  Q(description__icontains=query) |
                  Q(price__icontains=query) |
                  Q(tag__title__icontains=query)
                  )
        # tshirt, t-shirt, t shirt, red, green, blue,
        return self.filter(lookups).distinct()

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self): #Product.objects.featured() 
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id) # Product.objects == self.get_queryset()
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)


class Product(models.Model):
    title           = models.CharField(max_length=120)
    slug            = models.SlugField(blank=True, unique=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    image           = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured        = models.BooleanField(default=False)
    active          = models.BooleanField(default=True)
    #timestamp       = models.DateTimeField(auto_now_add=True)

    objects = ProductManager()

    def get_absolute_url(self):
        #return "/products/{slug}/".format(slug=self.slug)
        return reverse("products:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    @property
    def name(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

web-application/src/products/views.py
# from django.views import ListView
from django.http import Http404
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404

from carts.models import Cart

from .models import Product


class ProductFeaturedListView(ListView):
    template_name = "products/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()


class ProductFeaturedDetailView(DetailView):
    queryset = Product.objects.all().featured()
    template_name = "products/featured-detail.html"

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     return Product.objects.featured()



class ProductListView(ListView):
    template_name = "products/list.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     print(context)
    #     return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()


def product_list_view(request):
    queryset = Product.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "products/list.html", context)



class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        #instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("Uhhmmm ")
        return instance



class ProductDetailView(DetailView):
    #queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        # context['abc'] = 123
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Product.objects.get_by_id(pk)
        if instance is None:
            raise Http404("Product doesn't exist")
        return instance

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #     return Product.objects.filter(pk=pk)


def product_detail_view(request, pk=None, *args, **kwargs):
    # instance = Product.objects.get(pk=pk, featured=True) #id
    # instance = get_object_or_404(Product, pk=pk, featured=True)
    # try:
    #     instance = Product.objects.get(id=pk)
    # except Product.DoesNotExist:
    #     print('no product here')
    #     raise Http404("Product doesn't exist")
    # except:
    #     print("huh?")

    instance = Product.objects.get_by_id(pk)
    if instance is None:
        raise Http404("Product doesn't exist")
    #print(instance)
    # qs  = Product.objects.filter(id=pk)

    # #print(qs)
    # if qs.exists() and qs.count() == 1: # len(qs)
    #     instance = qs.first()
    # else:
    #     raise Http404("Product doesn't exist")

    context = {
        'object': instance
    }
    return render(request, "products/detail.html", context)

web-application/src/products/templates/products/snippets/card.html
{% extends "base.html" %}

{% load static %}
{% block content %}

<style type="text/css">
  .col-4
  {
    margin-right:40%;
  }


h5{
  font-family: 'Pacifico';
  color:black;
  position:absolute;
  font-size: 300%;
  
  letter-spacing: 4px;
  font-weight: 100;

  text-shadow: 0 8px 16px rgba(0,0,0,0.9);

  margin-bottom:10%;


}

.card {
  /* Add shadows to create the "card" effect */
  box-shadow: 0 0px 10px 5px rgba(0,0,0,0.7);
  transition: 1s;
  padding: 5px 5px 5px 5px;
  text-align: justify;
  position: relative;
  min-height: 75px;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
  box-shadow: 0 28px 42px 0 rgba(0,0,0,0.2);
}

.vxc
{
  font: 100 30px/1.5 'Pacifico', Helvetica, sans-serif;
  color: black;
  text-shadow: 1px 1px 0px rgba(0,0,0,0.1), 2px 2px 1px rgba(0,0,0,0.5);
  text-align: left;
}

p
{
  font: 400 22px/1.1 'Bangers';
  letter-spacing: 7px;

}

#myVideo {
  position: fixed;
  right: 0;
  bottom: 0;
  min-width: 100%;
  min-height: 100%;
 
  
</style>







  <div class="col-4">
<div class="card d-flex" style="width: 16rem;" style='min-height: 125px;'>
  {% if instance.image %}
    <a href="{{ instance.get_absolute_url }}"><img class="card-img-top" src="{{ instance.image.url }}" alt="{{ instance.title}} logo"></a>
    {% endif %}
  <div class="card-body">
    <h4 class="vxc">{{ instance.title }}</h4>
    <p class="card-text"><b>${{ instance.price }}</b></p>
    <a href="{{ instance.get_absolute_url }}" class="btn btn-success ">VIEW ME</a>
   <!--  <a href="{% url 'products:detail' slug=instance.slug  %}" class="btn btn-warning">URL shortcut</a> -->
  </div>
</div>
</div>


  

<!--<div class="card" style="width: 15rem;">
  {% if instance.image %}
    <a href="{{ instance.get_absolute_url }}">
    	<img class="" src="{{ instance.image.url }}" alt="{{ instance.title}} logo" width="227" height="170">
    </a>
    {% endif %}
  <div class="body">
    <h4 class="vxc">{{ instance.title }}</h4>
    
    <p class=""><b>${{ instance.price }}</b></p>
    <a href="{{ instance.get_absolute_url }}" class="btn btn-success">VIEW ME</a>-->
   <!--  <a href="{% url 'products:detail' slug=instance.slug  %}" class="btn btn-warning">URL shortcut</a> -->
 <!--</div>
  </div>
</div>
</div>-->
{% endblock %}

web-application/src/products/templates/products/snippets/update-cart.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ product.id }}' />
    
    {% if in_cart %}
        <button type='submit' class='btn btn-success' style="padding:8px;cursor: pointer;">Remove?</button>
    {% else %}
        {% if product in cart.products.all %}
            In cart <button type='submit' class='btn btn-success'>Remove?</button>
        {% else %}
            <button type='submit'  class='btn btn-success'>Add to cart</button>
        {% endif %}
    {% endif %}
</form>